[package]
name = "greed"
description = "A rust tool to automate trades 📈"

edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ncipollo/greed"
version = "0.1.1"

[dependencies]
